// Our Work Gallery - Dynamic Image Loading from Local Folder
// This script loads images from the "our work/" folder in the codebase
// Images are listed in our-work-images.json file (generated by scan-our-work.js script)

let whatsappNumber = '919135057508'; // Default number

// Load WhatsApp number from config
document.addEventListener('DOMContentLoaded', async () => {
    // Get WhatsApp number from env-config if available
    if (typeof window.envConfig !== 'undefined' && window.envConfig.config) {
        whatsappNumber = window.envConfig.config.whatsappNumber;
        console.log('WhatsApp Number loaded:', whatsappNumber);
    }
    
    // Setup floating WhatsApp button
    setupWhatsAppButton();
    
    await loadGalleryImages();
});

// Load all images from local folder via JSON manifest
async function loadGalleryImages() {
    const galleryGrid = document.getElementById('galleryGrid');
    const loadingIndicator = document.getElementById('loadingIndicator');
    const noImagesMessage = document.getElementById('noImagesMessage');

    try {
        // Load the images manifest JSON file
        const response = await fetch('our-work-images.json');
        
        if (!response.ok) {
            console.error('Could not load our-work-images.json');
            showNoImages();
            return;
        }

        const data = await response.json();
        
        if (!data.images || data.images.length === 0) {
            showNoImages();
            return;
        }

        // Hide loading, show gallery
        loadingIndicator.style.display = 'none';
        galleryGrid.style.display = 'grid';

        // Display each image in the gallery
        data.images.forEach(image => {
            const galleryItem = createGalleryItem(image);
            galleryGrid.appendChild(galleryItem);
        });

        console.log(`✅ Loaded ${data.images.length} images from "our work" folder`);

    } catch (error) {
        console.error('Error loading gallery:', error);
        showNoImages();
    }
}

// Create a gallery item element
function createGalleryItem(image) {
    const item = document.createElement('div');
    item.className = 'gallery-item';
    
    // Use the display name from the manifest (or filename as fallback)
    const displayName = image.displayName || image.filename.replace(/\.[^/.]+$/, '').replace(/_/g, ' ');
    const imageUrl = image.path;
    
    item.innerHTML = `
        <img src="${imageUrl}" alt="${displayName}" loading="lazy">
    `;
    
    // Add click event to open lightbox
    item.addEventListener('click', () => {
        openLightbox(imageUrl, displayName);
    });
    
    return item;
}

// Show no images message
function showNoImages() {
    document.getElementById('loadingIndicator').style.display = 'none';
    document.getElementById('noImagesMessage').style.display = 'block';
    document.getElementById('galleryGrid').style.display = 'none';
}

// Lightbox functionality
function openLightbox(imageUrl, imageName) {
    const lightbox = document.getElementById('lightbox');
    const lightboxImage = document.getElementById('lightboxImage');
    
    lightboxImage.src = imageUrl;
    lightboxImage.alt = imageName;
    
    lightbox.classList.add('active');
    document.body.style.overflow = 'hidden'; // Prevent scrolling
}

function closeLightbox() {
    const lightbox = document.getElementById('lightbox');
    lightbox.classList.remove('active');
    document.body.style.overflow = ''; // Restore scrolling
}

// Close lightbox on close button click
document.getElementById('closeLightbox').addEventListener('click', closeLightbox);

// Close lightbox when clicking outside the image
document.getElementById('lightbox').addEventListener('click', (e) => {
    if (e.target.id === 'lightbox') {
        closeLightbox();
    }
});

// Close lightbox on Escape key
document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') {
        closeLightbox();
    }
});

// Setup floating WhatsApp button
function setupWhatsAppButton() {
    const whatsappFloatBtn = document.getElementById('whatsappFloat');
    if (whatsappFloatBtn) {
        const whatsappMessage = encodeURIComponent('Hi, I\'m interested in your work');
        const whatsappUrl = `https://wa.me/${whatsappNumber}?text=${whatsappMessage}`;
        whatsappFloatBtn.href = whatsappUrl;
        console.log('WhatsApp float button URL:', whatsappUrl);
    }
}
